# Generated by Django 3.0.5 on 2020-04-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('level', models.SmallIntegerField(default=1, verbose_name='Level')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='_category_subcategories_+', to='product.Category', verbose_name='Subcategories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('size', models.CharField(max_length=1)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(upload_to='products/')),
                ('category', models.ManyToManyField(to='product.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
